name: Run Amazon Website Simple UI Tests

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

jobs:
  E2E-Test:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: E2E On Chrome
        uses: cypress-io/github-action@v4
        env:
          CYPRESS_email: sezertesting@gmail.com
          CYPRESS_password: testautomation59
        with:
          browser: chrome
          headed: true
          
      - name: Export Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: chrome-cypress-test-report
          path: |
            ./cypress/report